### PR TITLE
Lookup compression

### PR DESCRIPTION
**Pull request by wismill**
An issue with the use of `INLINE` for `generalCategory` was raised in [`base`](https://gitlab.haskell.org/ghc/ghc/-/issues/22949). The fix is easy and should probably be adapted to `unicode-data*` packages.

Then I wondered if we could go further and reduce the size of the `Addr#` literal. It turns out we can reduce its size by 80% with minor perf cost.

This is due to the fact that planes 4 to 13 are currently unused and uselessly bloat the literal; also planes 15 & 16 are reserved to PUA. So the trick is:
- To divide the literal in 2 (Planes 0-3, Plane 14)
- Check the range of the character to select either one of the previous literal or default values (`Co` or `Cn`).

### CODE REVIEW

**Comment by wismill** [comment]
We may apply the same trick to all such literals across the codebase.

**Comment by wismill** [comment]
I got great results with this MR, but it is too big. I am going to split it into multiple MR.

<details>
<summary>Benchmark for unicode-data:</summary>
<pre>
All
  Unicode.Char.Case
    isLowerCase
      unicode-data:   OK (0.63s)
        4.51 ms ± 115 μs,   0 B  allocated,   0 B  copied,  64 MB peak memory, 21% more than baseline
    isUpperCase
      unicode-data:   OK (1.01s)
        3.63 ms ±  44 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    toCaseFoldString
      unicode-data:   OK (0.80s)
        11.1 ms ± 176 μs,  24 MB allocated, 5.5 KB copied,  90 MB peak memory,       same as baseline
    toLowerString
      unicode-data:   OK (0.41s)
        10.3 ms ± 387 μs,  24 MB allocated, 5.5 KB copied,  90 MB peak memory, 10% less than baseline
    toTitleString
      unicode-data:   OK (0.43s)
        11.1 ms ± 416 μs,  24 MB allocated, 5.4 KB copied,  90 MB peak memory,       same as baseline
    toUpperString
      unicode-data:   OK (0.91s)
        13.2 ms ± 269 μs,  24 MB allocated, 5.3 KB copied,  90 MB peak memory,  6% less than baseline
  Unicode.Char.Case.Compat
    isLower
      unicode-data:   OK (1.27s)
        4.48 ms ± 118 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 17% less than baseline
    isUpper
      unicode-data:   OK (0.66s)
        4.67 ms ±  95 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    toLower
      unicode-data:   OK (0.62s)
        8.25 ms ± 197 μs,  16 MB allocated, 3.4 KB copied,  90 MB peak memory,  5% less than baseline
    toTitle
      unicode-data:   OK (0.67s)
        8.97 ms ± 186 μs,  16 MB allocated, 3.4 KB copied,  90 MB peak memory,       same as baseline
    toUpper
      unicode-data:   OK (0.66s)
        8.80 ms ± 251 μs,  16 MB allocated, 3.3 KB copied,  90 MB peak memory,       same as baseline
  Unicode.Char.General
    generalCategory
      unicode-data:   OK (0.97s)
        6.69 ms ±  90 μs,  16 MB allocated, 3.3 KB copied,  90 MB peak memory,       same as baseline
    isAlphabetic
      unicode-data:   OK (0.74s)
        4.94 ms ± 123 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% more than baseline
    isAlphaNum
      unicode-data:   OK (1.34s)
        4.71 ms ±  73 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 16% less than baseline
    isControl
      unicode-data:   OK (0.76s)
        5.13 ms ±  98 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isMark
      unicode-data:   OK (0.75s)
        4.99 ms ± 108 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  6% less than baseline
    isPrint
      unicode-data:   OK (0.71s)
        4.65 ms ± 145 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  7% less than baseline
    isPunctuation
      unicode-data:   OK (0.75s)
        4.96 ms ±  85 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  6% less than baseline
    isSeparator
      unicode-data:   OK (0.70s)
        4.57 ms ±  88 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% less than baseline
    isSymbol
      unicode-data:   OK (0.70s)
        4.97 ms ± 142 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  6% less than baseline
    isWhiteSpace
      unicode-data:   OK (0.39s)
        4.60 ms ± 172 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isHangul
      unicode-data:   OK (0.70s)
        4.59 ms ± 128 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% more than baseline
    isHangulLV
      unicode-data:   OK (0.71s)
        4.60 ms ± 120 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isJamo
      unicode-data:   OK (1.28s)
        4.61 ms ±  90 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% more than baseline
    jamoLIndex
      unicode-data:   OK (1.06s)
        3.62 ms ±  81 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    jamoVIndex
      unicode-data:   OK (1.06s)
        3.61 ms ±  96 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    jamoTIndex
      unicode-data:   OK (1.06s)
        3.61 ms ±  61 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
  Unicode.Char.General.Blocks
    block
      unicode-data:   OK (0.88s)
        287  ms ± 7.3 ms, 1.6 GB allocated, 311 KB copied,  90 MB peak memory,       same as baseline
    blockDefinition
      unicode-data:   OK (0.30s)
        8.71 μs ± 334 ns,  18 KB allocated,   3 B  copied,  90 MB peak memory,       same as baseline
  Unicode.Char.General.Compat
    isAlpha
      unicode-data:   OK (0.68s)
        4.65 ms ±  95 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% less than baseline
    isLetter
      unicode-data:   OK (0.71s)
        4.69 ms ± 138 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isSpace
      unicode-data:   OK (0.65s)
        4.64 ms ± 110 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 23% less than baseline
  Unicode.Char.Identifiers
    isIDContinue
      unicode-data:   OK (0.75s)
        4.96 ms ± 101 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  6% less than baseline
    isIDStart
      unicode-data:   OK (0.71s)
        4.70 ms ± 102 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isXIDContinue
      unicode-data:   OK (0.71s)
        4.70 ms ± 141 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    isXIDStart
      unicode-data:   OK (0.39s)
        5.49 ms ± 209 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 10% more than baseline
    isPatternSyntax
      unicode-data:   OK (0.71s)
        4.70 ms ± 134 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 14% less than baseline
    isPatternWhitespace
      unicode-data:   OK (0.70s)
        4.59 ms ±  86 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
  Unicode.Char.Normalization
    isCombining
      unicode-data:   OK (0.69s)
        4.94 ms ±  86 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  3% more than baseline
    combiningClass
      unicode-data:   OK (0.82s)
        6.08 ms ± 180 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  4% less than baseline
    isCombiningStarter
      unicode-data:   OK (0.33s)
        4.50 ms ± 169 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  5% less than baseline
    isDecomposable
      Canonical
        unicode-data: OK (0.74s)
          4.89 ms ± 118 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory, 10% less than baseline
      Kompat
        unicode-data: OK (2.69s)
          4.96 ms ± 182 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
    decompose
      Canonical
        unicode-data: OK (0.47s)
          26.3 ms ± 986 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,       same as baseline
      Kompat
        unicode-data: OK (0.51s)
          30.9 ms ± 701 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  3% less than baseline
    decomposeHangul
      unicode-data:   OK (0.53s)
        3.62 ms ±  93 μs,   0 B  allocated,   0 B  copied,  90 MB peak memory,  6% less than baseline
  Unicode.Char.Numeric
    isNumeric
      unicode-data:   OK (0.38s)
        10.6 ms ± 379 μs,   0 B  allocated,   0 B  copied,  91 MB peak memory,       same as baseline
    numericValue
      unicode-data:   OK (1.12s)
        8.15 ms ± 139 μs,   0 B  allocated,   0 B  copied,  91 MB peak memory,  3% less than baseline
    integerValue
      unicode-data:   OK (0.78s)
        10.6 ms ± 390 μs, 613 KB allocated, 168 B  copied,  91 MB peak memory,       same as baseline
  Unicode.Char.Numeric.Compat
    isNumber
      unicode-data:   OK (0.76s)
        4.97 ms ± 101 μs,   0 B  allocated,   0 B  copied,  91 MB peak memory,  6% less than baseline
</pre>
</details>

Note that I even reach improvement >30% on an older machine. My guess is that bechause the `Addr#` literal are shrunken they may fit the CPU cache.

**Comment by harendra-kumar** [comment]
I have not looked at the code yet. It may be worth doing if there are enough improvements that are, say, 7% or more and the added code complexity is manageable.

**Comment by wismill** [comment]
I think it should be done anyway: inlining huge literals is not a good idea (see issue in [GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/22949)).

Then I tried to fix regressions in two ways:
- reduce literal size
- do not use `generalCategory` directly.

**Comment by wismill** [comment]
Closing in favor of #105 and #106.

**Pull request closed without merging**
