### PR TITLE
Update to Unicode 15.0.0

### LINKED ISSUE #85: Update to Unicode 15.0.0
[Unicode 15.0.0](https://www.unicode.org/versions/Unicode15.0.0/) has been published.

Maybe wait for #82 ?

### PR DESCRIPTION
**Pull request by wismill**
Update to Unicode [`15.0.0`](https://www.unicode.org/versions/Unicode15.0.0/).

Fixes #85.

### CODE REVIEW

**Comment by wismill** [comment]
Note that since this version is not supported yet by any published GHC version, you need to use GHC `HEAD` or one of [my](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9045) [MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9035).

**Comment by wismill** [comment]
Rebased

**Comment by wismill** [comment]
@harendra-kumar kind reminder

**Comment by harendra-kumar** [comment]
Looks good to me. Though I only took a quick look, and I did not verify if we actually took the right unicode sources to generate the code. @adithyaov would you like to take a look as well?

**Review by adithyaov — APPROVED** [review]
LGTM

**Comment by wismill** [comment]
Candidates:
- [`unicode-data`](https://hackage.haskell.org/package/unicode-data-0.4.0/candidate)
- [`unicode-data-names`](https://hackage.haskell.org/package/unicode-data-names-0.2.0/candidate)
- [`unicode-data-scripts`](https://hackage.haskell.org/package/unicode-data-scripts-0.2.0/candidate)
- [`unicode-data-security`](https://hackage.haskell.org/package/unicode-data-security-0.2.0/candidate)

**Comment by wismill** [comment]
@harendra-kumar @adithyaov candidates published

**Comment by harendra-kumar** [comment]
@wismill I cannot find the candidates, the links above do not work.

**Comment by wismill** [comment]
@harendra-kumar I mean I published the new version, after the _candidate_ stage.

**Pull request merged**
