### PR TITLE
Add Unicode.Char.Case.Compat

### PR DESCRIPTION
**Pull request by wismill**
Add `Unicode.Char.Case.Compat` with toLower, toUpper and toTitle functions.

Fix `UnicodeData.txt` parsing.

This fixes the missing functions for drop-in replacement of `Data.Char` (see #47).

### CODE REVIEW

**Comment by harendra-kumar** [comment]
I am wondering if we should have a single `Unicode.Char.Compat` module instead of multiple compat modules in order to reduce the number of modules.

**Comment by wismill** [comment]
> I am wondering if we should have a single `Unicode.Char.Compat` module instead of multiple compat modules in order to reduce the number of modules.

I think this is the last `Compat` module; two of such modules seems reasonable.

**Review by adithyaov — APPROVED** [review]

**Comment by adithyaov** [comment]
Looks good!

**Comment by wismill** [comment]
I added benchmarks. We get a nice 3× speedup compared to `base`.

**Review by Bodigrim — APPROVED** [review]

**Pull request merged**
